### ISSUE TITLE
Can't search on Google

### ISSUE THREAD

**Issue by prcastro** [KELiON/cerebro#227]
Just built Cerebro on Arch Linux and I can't perform search on google. Launching apps and translating works. The results appear on the right panel, but when I hit enter on top of one of them, nothing happens.

**Comment by AlexAlabyev** [comment]
@prcastro the same thing on Win 10, search predictions list doesn't work

**Comment by carlos-wong** [comment]
macos too, 2.6 is work, after upgrade to 2.7 the enter action of google search suggest is nothing happen

**Comment by maximbaz** [comment]
```
TypeError: searchFn is not a function
    at onSelect (file:///usr/lib/cerebro/resources/app.asar/dist/main.bundle.js:28998:24)
```

Here:


	let Preview = class Preview extends _react.Component {
	  renderSuggestions(suggestions, searchFn) {
	    const className = [_styles2.default.wrapper, isStarWars(this.props.query) ? _styles2.default.starwars : ''].join(' ');
	    return _jsx('div', {
	      className: className
	    }, void 0, _jsx(_KeyboardNav2.default, {}, void 0, _jsx('ul', {
	      className: _styles2.default.list
	    }, void 0, suggestions.map(s => _jsx(_KeyboardNavItem2.default, {
	      tagName: 'li',
	      onSelect: () => searchFn(s)         <------------------------------
	    }, s, s)))));

**Comment by carlos-wong** [comment]
I am sure this function is work on 0.2.6 versioin

**Comment by KELiON** [comment]
```
TypeError: searchFn is not a function
    at onSelect (file:///usr/lib/cerebro/resources/app.asar/dist/main.bundle.js:28998:24)
```

🤔 looks like it is again something related to react-optimize plugin. I'll take a look

**Comment by antonreshetov** [comment]
Также не работает поиск из списка

**Comment by DrNightmare** [comment]
Downloaded and ran the AppImage for Cerebro (Ubuntu 16.04, 64-bit). I can press Enter to search on Google whatever term I've typed in the input field, but am unable to search for the suggestions that show up as I'm typing, on the right hand side. When I focus on one of the suggestions and press Enter, nothing happens.

**Comment by KELiON** [comment]
`cerebro-git` package should be fixed now, in other platforms fix will be included in next release (#239)
